name: cuida_pet_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  args: ^2.0.0
  logger: ^1.3.0
  mysql_client: ^0.0.27
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  get_it: ^7.2.0
  injectable: ^2.1.1
  jaguar_jwt: ^3.0.0
  dartenv: ^1.0.2

dev_dependencies:
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
  shelf_router_generator: ^1.0.5
